stages:
  - test
  - docker_build
test:
  image: "python:3"
  stage: test
  script:
  - make test
  - make lint
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
  - apk add --update make
  - make docker_build
