stages:
- test
- apk add --update make
- make docker_build
test:
  image: "python:3"
  stage: test
  script:
  - make deps
  - PYTHONPATH=. py.test --verbose -s
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
  - docker build -t myapp .
