stages:
  - test
test:
  image: "python:3"
  stage: test
  script:
  - apk add --update make
  - make deps
  - make docker_build
  - PYTHONPATH=. py.test --verbose -s
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
  - docker build -t myapp .
