language: python
services:
  - docker
install:
  - make deps
script:
  - make test
  - make lint
  - make test_cov
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: fierce-garden-20344
  api_key: ${HEROKU_API_KEY}
